### ISSUE TITLE
Trying to use this config but getting errors on init

### ISSUE THREAD

**Issue by avivelmakias1** [askfiy/SimpleNvim#1]
Hi!
I've just cloned your repo and tried to use it, but i got some errors.
I'm using neovim version 0.9.1, so if it's the issue LMK.
just after cloning i got this issue:
```E5113: Error while calling lua chunk: vim/_meta.lua:0: Invalid option (not found): 'smoothscroll'```
so i guessed it was something with the options, after commenting it out i got this issue:
```/.config/simplenvim/lua/core/depends/lazy/init.lua:45: attempt to index field 'uv' (a nil value)```

am i just using the wrong version of neovim?

**Comment by askfiy** [comment]
Try using the pre-release version of 0.10. You can use Bob to install the latest version.
