### ISSUE TITLE
从知乎慕名前来，似乎使用遇到了些问题

### ISSUE THREAD

**Issue by handy-sun** [askfiy/SimpleNvim#2]
仓库内容克隆到 ~/.config/nvim 下，然后启动nvim，提示如下错误：

Error detected while processing /home/qi/.config/nvim/init.lua:
E5113: Error while calling lua chunk: vim/_meta.lua:0: Invalid option (not found): 'smoothscroll'
stack traceback:
        [C]: in function 'nvim_get_option_info'
        vim/_meta.lua: in function '__index'
        vim/_meta.lua: in function ''
        vim/_meta.lua: in function '__newindex'
        /home/qi/.config/nvim/lua/conf/preference.lua:19: in main chunk
        [C]: in function 'require'
        /home/qi/.config/nvim/lua/core/setting.lua:5: in main chunk
        [C]: in function 'require'
        /home/qi/.config/nvim/init.lua:3: in main chunk
Press ENTER or type command to continue

**Comment by askfiy** [comment]
https://github.com/askfiy/SimpleNvim/issues/1
