### ISSUE TITLE
Error while calling lua chunk: ...Neovim/nvim-linux64/share/nvim/runtime/lua/vim/_meta.lua:660: Not a valid option name: smoothscroll

### ISSUE THREAD

**Issue by LibraStalker** [askfiy/SimpleNvim#3]
下载配置后打开nvim提示Error while calling lua chunk: ...Neovim/nvim-linux64/share/nvim/runtime/lua/vim/_meta.lua:660: Not a valid option name: smoothscroll，这是为啥呀，nvim版本是v0.5.0

**Comment by askfiy** [comment]
https://github.com/askfiy/SimpleNvim/issues/1
