### ISSUE TITLE
E5113: Error while calling lua chunk: /root/.config/nvim/lua/core/depends/lazy/init.lua:67: module 'lazy' not found:

### ISSUE THREAD

**Issue by LibraStalker** [askfiy/SimpleNvim#4]
已经安装nvim 0.10，git版本为2.36，但是进入nvim还是显示lazy模块找不到，请问如何解决呀
E5113: Error while calling lua chunk: /root/.config/nvim/lua/core/depends/lazy/init.lua:67: module 'lazy' not found:
![image](https://github.com/askfiy/SimpleNvim/assets/43614586/fa53baab-23c5-4341-830f-2f87c1c66136)

**Comment by LibraStalker** [comment]
已解决，之前网络问题导致lazy.nvim没下载完成，/root/.local/share/nvim/depends/lazy.nvim是空的，删除该文件夹，然后重新进入nvim就会重新下载lazy.nvim了。
参考：https://www.reddit.com/r/neovim/comments/11gvquf/module_lazy_not_found/

**Comment by askfiy** [comment]
👍🏻
